#!/bin/bash

cat << "EOF"

         ┃┃┏┫┓┏┏┓╋
         ┗┛┗┻┗┫┗┻┗
       Version: 1.3

EOF

HOST=$1
START=$2
END=$3
BANNER=""
STATUS=""
if [ -z "$HOST" ] || [ -z "$START" ] || [ -z "$END" ] ; then
  echo " Usage: $0 [IP_TARGET] [START PORT] [END PORT]"
  echo " Example: $0 192.x.x.x/24 1 100 "
  exit 1
elif [ "$START" -gt "$END" ]; then
  echo " the start need to be less than the end... "
  exit 1
fi


IP_BASE=$(echo "$HOST" | cut -d'/' -f1)
SUBMASK=$(echo "$HOST" | cut -d'/' -f2)

IFS='.' read -r O1 O2 O3 O4 <<< "$IP_BASE"

for OCTET in "$O1" "$O2" "$O3" "$O4"; do
    if ! [[ "$OCTET" =~ ^[0-9]+$ ]] || [ "$OCTET" -gt 255 ]; then
        echo "Try to input a valid IPv4 address."
        exit 1
    fi
done

get_status() {
  HEADERS=$(curl -skI "http$ts://$CURRENT_IP:$PORT")
  STATUS=$(echo "$HEADERS" | head -n 1)
  BANNER=$(echo "$HEADERS" | grep -i "^Server:")
}

generate_ip() {
  if [ "$SUBMASK" == "24" ] || [ "$SUBMASK" == "" ]; then
    for j in $(seq 1 254); do
      echo "$O1.$O2.$O3.$j"
    done
  elif [ "$SUBMASK" == '16' ]; then
    echo "WARNING: /16 network selected. This may generate a large number of connection attempts. Continue? [y/N]"
    read resposta
      case "$resposta" in
          y)
            for j in $(seq 0 255); do
              for f in $(seq 1 254); do
                echo "$O1.$O2.$j.$f"
            done
          done
          ;;
          N|"")
            echo "Canceling..."
            ;;
          *)
            echo "Invalid option..."
            exit 1
            ;;
      esac
    else echo "Unavailable prefix, only accept /24 or /16 "
    exit 1
  fi
}

echo "𓂀 SCANNING $HOST FROM $START UNTIL $END 𓂀"

while read -r CURRENT_IP; do
  for PORT in $(seq "$START" "$END"); do
    if (timeout 2 bash -c "echo > /dev/tcp/$CURRENT_IP/$PORT") 2>/dev/null; then
      case $PORT in
        21) EXPECTED_SERVICE="FTP" ;;
        22) EXPECTED_SERVICE="SSH" ;;
        23) EXPECTED_SERVICE="TELNET" ;;
        25) EXPECTED_SERVICE="SMTP" ;;
        53) EXPECTED_SERVICE="DNS" ;;
        80) EXPECTED_SERVICE="HTTP" ;;
        110) EXPECTED_SERVICE="POP3" ;;
        143) EXPECTED_SERVICE="IMAP" ;;
        443) EXPECTED_SERVICE="HTTPS" ;;
        445) EXPECTED_SERVICE="SMB" ;;
        3306) EXPECTED_SERVICE="MYSQL" ;;
        3389) EXPECTED_SERVICE="RDP" ;;
        5432) EXPECTED_SERVICE="POSTGRESQL" ;;
        8080) EXPECTED_SERVICE="HTTP-ALT" ;;
        *) EXPECTED_SERVICE="UNKNOWN" ;;
      esac
      ts=""
      if [ "$PORT" == "80" ] || [ "$PORT" == "443" ]; then

        if [ "$PORT" == "443" ]; then
          ts="s"
          else
            ts=""
        fi
          get_status
      else
        exec 3<>/dev/tcp/$CURRENT_IP/$PORT
        echo "A" >&3
        timeout 3 read -r -u 3 BANNER
        exec 3>&-
      fi
      if [ -z "$BANNER" ]; then
        BANNER="UNKNOWN"
      fi
      echo "IP: $CURRENT_IP PORT $PORT: OPEN"
      echo "EXPECTED: $EXPECTED_SERVICE"
      echo "BANNER: $BANNER"
      if [ "$PORT" == "443" ] || [ "$PORT" == "80" ]; then
        echo "STATUS: $STATUS"
      fi
      BANNER=""
      STATUS=""
    fi
  done
done < <(generate_ip)
echo "__________________SCAN FINISHED____________________"


